services:
  - type: web
    name: chatgpt-docker-plugin
    runtime: docker
    repo: https://github.com/GlassOnTin/docker-ubuntu-ssh/tree/master
    envVars:
      - key: SSH_PORT
        value: "22"
      - key: API_PORT
        value: "3000"
    disk:
      name: chatgpt-data
      mountPath: /home/devuser
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true

envVarGroups:
  - name: chatgpt-settings
    envVars:
      - key: CONCURRENCY
        value: "2"
